fix: メタデータ categories の修正
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 400 Bad Request): The following category slugs are not currently supported on crates.io: network, chat, websocket

  See https://crates.io/category_slugs for a list of supported slugs.